// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function MarkSentToAI() {
  return window['go']['main']['App']['MarkSentToAI']();
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function UpdateContent(arg1) {
  return window['go']['main']['App']['UpdateContent'](arg1);
}
